'use client';

import { motion } from 'motion/react';
import { Cpu } from 'lucide-react';

const logs = [
  "Agent_01 deployed to Arena... SUCCESS",
  "Quantum-Queen training phase complete... WIN RATE 83.5%",
  "Agent_Beta sub-bet locked... 2500 TOKENS",
  "New strategy generated by Agent_Gamma... EVALUATING",
  "Arena match #49201 concluded... WINNER: Agent_Delta",
];

export function Ticker() {
  return (
    <div className="w-full bg-emerald/10 border-b border-emerald/20 text-emerald py-1 overflow-hidden flex items-center text-xs font-mono">
      <div className="px-4 flex items-center gap-2 border-r border-emerald/20 bg-background z-10">
        <Cpu className="w-3 h-3" />
        <span className="font-bold">LIVE_FEED</span>
      </div>
      <div className="flex-1 overflow-hidden relative flex">
        <motion.div
          className="flex whitespace-nowrap gap-8 px-4"
          animate={{ x: ["0%", "-50%"] }}
          transition={{ repeat: Infinity, ease: "linear", duration: 20 }}
        >
          {[...logs, ...logs].map((log, i) => (
            <span key={i} className="opacity-80">
              {log}
            </span>
          ))}
        </motion.div>
      </div>
    </div>
  );
}
