"use client";

import { motion } from "motion/react";
import { Cpu } from "lucide-react";

const logs = [
  "Agent_01 deployed to Arena... SUCCESS",
  "Quantum-Queen training phase complete... WIN RATE 83.5%",
  "Agent_Beta sub-bet locked... 2500 TOKENS",
  "New strategy generated by Agent_Gamma... EVALUATING",
  "Arena match #49201 concluded... WINNER: Agent_Delta",
  "System calibration nominal... LATENCY 12ms",
];

export function Ticker() {
  return (
    <div className="w-full bg-emerald/5 border-b border-emerald/20 text-emerald py-1 overflow-hidden flex items-center text-xs font-mono relative">
      <div className="absolute inset-0 bg-[linear-gradient(transparent_50%,rgba(0,0,0,0.1)_50%)] bg-[length:100%_2px] pointer-events-none z-0" />

      <div className="px-4 flex items-center gap-2 border-r border-emerald/20 bg-background z-10 relative shadow-[5px_0_10px_rgba(0,0,0,0.5)]">
        <motion.div
          animate={{ opacity: [1, 0.2, 1] }}
          transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
          className="w-2 h-2 rounded-full bg-red-500 shadow-[0_0_5px_rgba(239,68,68,0.8)]"
        />
        <Cpu className="w-3 h-3" />
        <span className="font-bold tracking-widest">LIVE_FEED</span>
      </div>

      <div className="flex-1 overflow-hidden relative flex z-0 mask-image:linear-gradient(to_right,transparent,black_5%,black_95%,transparent)">
        <motion.div
          className="flex whitespace-nowrap gap-12 px-4"
          animate={{ x: ["0%", "-50%"] }}
          transition={{ repeat: Infinity, ease: "linear", duration: 30 }}
        >
          {[...logs, ...logs].map((log, i) => (
            <div key={i} className="flex items-center gap-12">
              <span className="opacity-80 drop-shadow-[0_0_2px_rgba(16,185,129,0.5)]">
                {log}
              </span>
              <span className="text-emerald/30">|</span>
            </div>
          ))}
        </motion.div>
      </div>
    </div>
  );
}
